### ISSUE TITLE
Hide week number

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt2#25]
how do i hide the week number
![calendar](https://user-images.githubusercontent.com/41309095/62342845-2d09e880-b49d-11e9-986d-1d903ef79390.jpg)

**Comment by eouia** [comment]
Add this into your `css/custom.css` (after `body { }`)

```css
.CX2 .weeksmark {
  display:none;
}
```
