### ISSUE TITLE
Show location

### ISSUE THREAD

**Issue by ingo916** [eouia/MMM-CalendarExt2#26]
How do i show the location info for the calendar event?

**Comment by eouia** [comment]
in which view? Commonly in `month` and `week` view, events area is too small to display location or description in 1 row, so I don't recommend. I suggest using other supporting views together additionally.
In other views, add this into your `css/custom.css`

```css

.CX2 .timeline .eventSub {
  display:none;
}

.CX2 .eventSub {
  display:block;
}

.CX2 .eventSub * {
  display:none;
}

.CX2 .eventSub .eventLocation {
  display:block;
}
```
