### ISSUE TITLE
Show end times on calendar

### ISSUE THREAD

**Issue by jbf101** [eouia/MMM-CalendarExt2#53]
I have read through the guide about 50 times and for the life of me I cant figure out how to have the calendar show end times.

My setup is very simple, default view on most things. I just want the default week view to show the end times of events.

**Comment by eouia** [comment]
each cell of week/month view is too narrow to display end time of an event, so I don't recommend it.
If you want to reveal it anyway, by CSS modification it could be possible. 
```css
.CX2 .weekSlot .event:not(.fullday) .endTime {
  display:inline;
}
```
Add this into your `css/custom.css`,
