### ISSUE TITLE
Question: Upcoming view, one line event

### ISSUE THREAD

**Issue by GattoJohnny** [eouia/MMM-CalendarExt2#59]
Hi Sean,

Can I make eventTitle and eventTime appear in the same line in Upcoming view? I have enough width and limited height so it would be nice to save some space by displaying them in one line rather then broken down into two. Do you have a CSS trick to achieve this?

Cheers,
Gyorgy

**Comment by eouia** [comment]
Some more adjusting might be needed for your environment, but basic concept would be this;
```css
.CX2 .upcoming .event .eventIcon {
  width:16px;
  height:16px;
  min-width:inherit;
  min-height:inherit;
}

.CX2 .upcoming .event .eventMain {
  display:flex;
  flex-direction:row;
  justify-content: space-between;
}

.CX2 .upcoming .event .eventTitle {
  width:45%;
}

.CX2 .upcoming .event .eventTime {
  width:45%;
}
```
![image](https://user-images.githubusercontent.com/1720610/75228110-cd17be00-57af-11ea-80af-676e710c74a9.png)
